#
# Serve assets:
#   KEYSERVER_PATH=$PWD docker compose -f docker-compose.yaml up site
#
# Create assets:
#   KEYSERVER_PATH=$PWD docker compose -f docker-compose.yaml run --rm create
#
# Request assets:
#   KEYSERVER_PATH=$PWD docker compose -f docker-compose.yaml run --rm request

name: keyserver

services:
  site:
    image: keyserver:latest

    command: >
      python3 scripts/kssite.py 

    environment:
    - KSSITE_CONFIG_PATH=/home/keyserver/conf/kssite.yaml

    ports:
    - "8022:8022"

    volumes:
    - conf:/home/keyserver/conf
    - assets:/home/keyserver/assets

    stop_grace_period: 1s

  create:
    image: keyserver:latest

    command: >
      python3 scripts/kscreate.py

    environment:
    - KSCREATE_CONFIG_PATH=/home/keyserver/conf/kscreate.yaml
    - KSCREATE_KEYS_PATH=/home/keyserver/keys

    volumes:
    - conf:/home/keyserver/conf
    - keys:/home/keyserver/keys
    - assets:/home/keyserver/assets
    - logs:/home/keyserver/logs

    stop_grace_period: 1s

  request:
    image: keyserver:latest

    command: >
      python3 scripts/ksrequest.py

    environment:
    - KSREQUEST_CONFIG_PATH=/home/keyserver/conf/ksrequest.yaml

    volumes:
    - conf:/home/keyserver/conf
    - logs:/home/keyserver/logs


volumes:
  stub: 
    driver_opts: &dopt
      o: bind
      type: local
      device: ${KEYSERVER_PATH}

  assets:
    driver_opts: 
      <<: *dopt
      device: ${KEYSERVER_PATH}/assets

  conf:
    driver_opts:
      <<: *dopt
      device: ${KEYSERVER_PATH}/conf

  logs:
    driver_opts:
      <<: *dopt
      device: /var/log/scaffold

  keys:
    driver_opts:
      <<: *dopt
      device: /home/dnlennon/.ssh/keys/mrdl

