# KEYSERVER_HOME=$PWD docker-compose -f docker-compose.yaml up -d

services:
  web:
    container_name: keyserver.service

    # image: "busybox:1.36.1-glibc"
    build: .

    command: "httpd -v -f -h /var/www/html"

    ports:
      - "8022:80"

    volumes:
      - type: bind
        source: ${KEYSERVER_HOME}/www
        target: /var/www

    stop_grace_period: 1s
