name: keyserver

services:
  site:
    # KEYSERVER_PATH=$PWD docker compose -f docker-compose.yaml up site
    image: "busybox:1.36.1-glibc"

    command: "httpd -v -f -h /home/keyserver/assets"

    ports:
    - "8022:80"

    volumes:
    - assets:/home/keyserver/assets

    stop_grace_period: 1s

  generator:
    # KEYSERVER_PATH=$PWD docker compose -f docker-compose.yaml run --rm generator
    image: keyserver-service:latest

    command: >
      python3 scripts/generate.py 
        --config ./conf/keyserver.yaml

    environment:
    - KEYSERVER_KEYS_PATH=/home/keyserver/keys
    - KEYSERVER_ASSETS_PATH=/home/keyserver/assets

    volumes:
    - keys:/home/keyserver/keys
    - assets:/home/keyserver/assets
    - logs:/home/keyserver/logs

    stop_grace_period: 1s

volumes:
  assets:
    driver_opts:
      o: bind
      type: local
      device: ${KEYSERVER_PATH}/assets

  logs:
    driver_opts:
      o: bind
      type: local
      device: ${KEYSERVER_PATH}/logs

  keys:
    driver_opts:
      o: bind
      type: local
      device: /home/dnlennon/.ssh/keys/mrdl

